- name: install basic packages that web-server (nginx) must have to work
  apt: pkg={{item}} update_cache=yes cache_valid_time=64000
  sudo: True
  with_items:
    - nginx
    - php5-cli
    - php5-fpm

- include: nginx.yml
